name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Fix file permissions
      run: chmod +x ./node_modules/.bin/* || true

    - name: Install System Dependencies
      run: |
        sudo apt-get update --allow-releaseinfo-change
        sudo apt-get install -y \
          libasound2t64 \
          libicu-dev \
          libffi-dev \
          libx264-dev \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libgbm1 \
          libgtk-3-0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libpangocairo-1.0-0
        
    - name: Install dependencies
      run: npm install --unsafe-perm
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run the Program
      run: npm run start &

    - name: Run server
      run: npm run server &

    - name: Wait for Server to Start
      run: sleep 10
      
    - name: Run integration tests
      run: npx playwright test
